name: "File Editor Plus"
version: "0.2.49"
slug: "file_editor_plus"
description: "Pro File Editor for Home Assistant"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: application
boot: auto
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin

ingress: true
ingress_port: 8099
ingress_panel: true
panel_title: File Editor Plus
ports:
  8099/tcp: null
panel_icon: "mdi:file-document-edit-outline"

map:
  - config:rw

options: {}
schema: {}
