name: "File Editor Plus (MVP)"
version: "0.1.6"
slug: "file_editor_plus"
description: "Pro File Editor for Home Assistant"
arch:
  - amd64
startup: application
boot: auto
init: false

ingress: true
ingress_port: 8099
ports:
  8099/tcp: null
panel_icon: "mdi:file-document-edit-outline"

# Per ora niente permessi strani: MVP super safe
map:
  - config:rw

options: {}
schema: {}
